# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tela_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 549)
        font = QtGui.QFont()
        font.setPointSize(13)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_login = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_login.setGeometry(QtCore.QRect(230, 380, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 0, 127);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;")
        self.pushButton_login.setObjectName("pushButton_login")
        self.lineEdit_login = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_login.setGeometry(QtCore.QRect(150, 220, 271, 41))
        self.lineEdit_login.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.lineEdit_login.setText("")
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.lineEdit_senha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_senha.setGeometry(QtCore.QRect(150, 300, 271, 41))
        self.lineEdit_senha.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.lineEdit_senha.setText("")
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 470, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 0, 127);")
        self.label.setObjectName("label")
        self.pushButton_cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cadastrar.setGeometry(QtCore.QRect(300, 460, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_cadastrar.setFont(font)
        self.pushButton_cadastrar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 0, 127);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;")
        self.pushButton_cadastrar.setObjectName("pushButton_cadastrar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 210, 31, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(r"Interfaces\User.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 280, 31, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(r"Interfaces\Locker.png"))
        self.label_3.setObjectName("label_3")
        self.label_message = QtWidgets.QLabel(self.centralwidget)
        self.label_message.setGeometry(QtCore.QRect(170, 350, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_message.setFont(font)
        self.label_message.setStyleSheet("color: rgb(85, 0, 127);")
        self.label_message.setText("")
        self.label_message.setObjectName("label_message")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(180, 0, 201, 181))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(r"Interfaces\Logo framework.jpg"))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 230, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(85, 0, 127);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 310, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(85, 0, 127);")
        self.label_7.setObjectName("label_7")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(425, 310, 70, 17))
        self.checkBox.setObjectName("checkBox")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(440, 300, 31, 41))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(r"Interfaces\16672732291582692233-32.png"))
        self.label_4.setObjectName("label_4")
        self.label_2.raise_()
        self.pushButton_login.raise_()
        self.lineEdit_login.raise_()
        self.lineEdit_senha.raise_()
        self.label.raise_()
        self.pushButton_cadastrar.raise_()
        self.label_3.raise_()
        self.label_message.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.checkBox.raise_()
        self.label_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.pushButton_login.setText(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "Nao possui cadastro?"))
        self.pushButton_cadastrar.setText(_translate("MainWindow", "CADASTRAR"))
        self.label_6.setText(_translate("MainWindow", "USUARIO:"))
        self.label_7.setText(_translate("MainWindow", "SENHA:"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))