# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'padawansproject.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(422, 535)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_t1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_t1.setGeometry(QtCore.QRect(90, 290, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_t1.setFont(font)
        self.pushButton_t1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 0, 127);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;")
        self.pushButton_t1.setObjectName("pushButton_t1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 0, 201, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(r"Interfaces\Logo framework.jpg"))
        self.label.setObjectName("label")
        self.pushButton_t2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_t2.setGeometry(QtCore.QRect(90, 340, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_t2.setFont(font)
        self.pushButton_t2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 0, 127);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;")
        self.pushButton_t2.setObjectName("pushButton_t2")
        self.pushButton_t3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_t3.setGeometry(QtCore.QRect(90, 390, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_t3.setFont(font)
        self.pushButton_t3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 0, 127);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;")
        self.pushButton_t3.setObjectName("pushButton_t3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 200, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(85, 0, 127);")
        self.label_2.setObjectName("label_2")
        self.pushButton_logout = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_logout.setGeometry(QtCore.QRect(280, 460, 111, 41))
        self.pushButton_logout.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 0, 127);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;")
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.label_welcome = QtWidgets.QLabel(self.centralwidget)
        self.label_welcome.setGeometry(QtCore.QRect(115, 230, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_welcome.setFont(font)
        self.label_welcome.setStyleSheet("color: rgb(85, 0, 127);")
        self.label_welcome.setText("")
        self.label_welcome.setObjectName("label_welcome")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 422, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Padawan\'s Project"))
        self.pushButton_t1.setText(_translate("MainWindow", "Irmã"))
        self.pushButton_t2.setText(_translate("MainWindow", "Família"))
        self.pushButton_t3.setText(_translate("MainWindow", "Momento descontração"))
        self.label_2.setText(_translate("MainWindow", "Padawans Episódio VI"))
        self.pushButton_logout.setText(_translate("MainWindow", "LOGOUT"))